FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
ENV COREPACK_ENABLE_STRICT=0
COPY . /app
WORKDIR /app

ENV COREPACK_ENABLE_STRICT=0
RUN pnpm install
RUN pnpm run build || true

RUN apt-get update && apt-get install -y \
      chromium \
      fonts-noto \
      libxss1 \
      --no-install-recommends && \
      rm -rf /var/lib/apt/lists/*


# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
ENV SITE="https://pablos-test-site-516ce7.webflow.io"
ENV OUTPUT_PATH="/files/goreplay"

# RUN chown root:root /usr/lib/chromium/chrome-sandbox && \
#     chmod 4755 /usr/lib/chromium/chrome-sandbox

# # Add user so we don't need --no-sandbox.
# RUN addgroup -S unlighthouse && adduser -S -G unlighthouse unlighthouse \
#     && mkdir -p /home/unlighthouse/Downloads /app \
#     && chown -R unlighthouse:unlighthouse /home/unlighthouse \
#     && chown -R unlighthouse:unlighthouse /app

# Run everything after as non-privileged user.
USER root
RUN mkdir files
CMD pnpm run ci --site ${SITE} --build-static --output-path ${OUTPUT_PATH}

